name: Build Job
on: 
 # push:
   # branches: 
   #   - main
   pull_request:
     branches:
      - main
   Permissions:
     contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war
      - name: Notify if build fails
        if: failure()
        run: echo "Build failed. Please check the logs for details."


  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle